"""org branding theme accent

Revision ID: 333137dcc702
Revises: c9e2aaea2e26
Create Date: 2026-07-19 18:19:47.076807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '333137dcc702'
down_revision: Union[str, None] = 'c9e2aaea2e26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('theme', sa.String(length=10), server_default='light', nullable=False))
    op.add_column('organizations', sa.Column('accent_color', sa.String(length=9), server_default='#2563eb', nullable=False))
    op.add_column('organizations', sa.Column('keep_branding', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'keep_branding')
    op.drop_column('organizations', 'accent_color')
    op.drop_column('organizations', 'theme')
    # ### end Alembic commands ###
