"""line discount type and value

Revision ID: 3a2c3b772a4e
Revises: 0bf6069141bf
Create Date: 2026-07-22 05:12:18.291610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a2c3b772a4e'
down_revision: Union[str, None] = '0bf6069141bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('document_lines', sa.Column('discount_type', sa.String(length=10), nullable=True))
    op.add_column('document_lines', sa.Column('discount_value', sa.Numeric(precision=18, scale=2), nullable=True))
    op.execute("UPDATE document_lines SET discount_type = 'amount', discount_value = discount")
    op.alter_column('document_lines', 'discount_type', nullable=False)
    op.alter_column('document_lines', 'discount_value', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_lines', 'discount_value')
    op.drop_column('document_lines', 'discount_type')
    # ### end Alembic commands ###
