"""sales orders delivery challans stock posted

Revision ID: 3ff67b6daa52
Revises: 1aacd6ca2464
Create Date: 2026-07-22 18:34:50.823187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ff67b6daa52'
down_revision: Union[str, None] = '1aacd6ca2464'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('stock_posted', sa.Boolean(), nullable=True))
    # Backfill from the ledger: a document moved stock if it has movements.
    op.execute(
        "UPDATE documents SET stock_posted = EXISTS ("
        "  SELECT 1 FROM stock_movements sm"
        "  WHERE sm.reference_type = documents.type AND sm.reference_id = documents.id"
        ")"
    )
    op.alter_column('documents', 'stock_posted', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'stock_posted')
    # ### end Alembic commands ###
