"""org industry fiscal logo

Revision ID: 54fe7fcf0452
Revises: 694eb338ee1c
Create Date: 2026-07-19 18:06:01.935014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54fe7fcf0452'
down_revision: Union[str, None] = '694eb338ee1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('industry', sa.String(length=100), nullable=True))
    op.add_column('organizations', sa.Column('fiscal_year_start_month', sa.Integer(), server_default='7', nullable=False))
    op.add_column('organizations', sa.Column('logo_url', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'logo_url')
    op.drop_column('organizations', 'fiscal_year_start_month')
    op.drop_column('organizations', 'industry')
    # ### end Alembic commands ###
