"""replace document_sequences with settings

Revision ID: 7df4628a5b77
Revises: ac9bd815e6b6
Create Date: 2026-07-24 05:13:58.915580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7df4628a5b77'
down_revision: Union[str, None] = 'ac9bd815e6b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('group', sa.String(length=50), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'group', 'key', name='uq_setting_org_group_key')
    )
    op.create_index('ix_settings_org_group', 'settings', ['org_id', 'group'], unique=False)
    op.create_index(op.f('ix_settings_org_id'), 'settings', ['org_id'], unique=False)
    op.drop_index(op.f('ix_document_sequences_org_id'), table_name='document_sequences')
    op.drop_table('document_sequences')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_sequences',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('prefix', sa.VARCHAR(length=12), autoincrement=False, nullable=False),
    sa.Column('next_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('padding', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('document_sequences_org_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('document_sequences_pkey')),
    sa.UniqueConstraint('org_id', 'type', name=op.f('uq_document_sequence_org_type'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_document_sequences_org_id'), 'document_sequences', ['org_id'], unique=False)
    op.drop_index(op.f('ix_settings_org_id'), table_name='settings')
    op.drop_index('ix_settings_org_group', table_name='settings')
    op.drop_table('settings')
    # ### end Alembic commands ###
