"""credit note settled amount

Revision ID: 9b4b53afc7b0
Revises: 3ff67b6daa52
Create Date: 2026-07-22 20:29:19.695433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b4b53afc7b0'
down_revision: Union[str, None] = '3ff67b6daa52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('settled_amount', sa.Numeric(precision=18, scale=2), nullable=True))
    op.execute("UPDATE documents SET settled_amount = 0")
    op.alter_column('documents', 'settled_amount', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'settled_amount')
    # ### end Alembic commands ###
