"""fbr reference data and org tokens

Revision ID: ac9bd815e6b6
Revises: 9b4b53afc7b0
Create Date: 2026-07-24 04:27:28.594866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac9bd815e6b6'
down_revision: Union[str, None] = '9b4b53afc7b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fbr_reference_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('value', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('parent_type', sa.String(length=30), nullable=True),
    sa.Column('parent_code', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type', 'code', 'parent_code', name='uq_fbr_reference_type_code_parent')
    )
    op.create_index('ix_fbr_reference_parent', 'fbr_reference_data', ['parent_type', 'parent_code'], unique=False)
    op.create_index('ix_fbr_reference_type', 'fbr_reference_data', ['type'], unique=False)
    op.add_column('organizations', sa.Column('fbr_enabled', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('organizations', sa.Column('fbr_environment', sa.String(length=12), server_default='sandbox', nullable=False))
    op.add_column('organizations', sa.Column('fbr_sandbox_token', sa.Text(), nullable=True))
    op.add_column('organizations', sa.Column('fbr_production_token', sa.Text(), nullable=True))
    op.add_column('organizations', sa.Column('fbr_province', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'fbr_province')
    op.drop_column('organizations', 'fbr_production_token')
    op.drop_column('organizations', 'fbr_sandbox_token')
    op.drop_column('organizations', 'fbr_environment')
    op.drop_column('organizations', 'fbr_enabled')
    op.drop_index('ix_fbr_reference_type', table_name='fbr_reference_data')
    op.drop_index('ix_fbr_reference_parent', table_name='fbr_reference_data')
    op.drop_table('fbr_reference_data')
    # ### end Alembic commands ###
