"""org-level attributes and normalized variants

Revision ID: af1c241df998
Revises: 6408e893ef66
Create Date: 2026-07-19 20:31:21.204400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'af1c241df998'
down_revision: Union[str, None] = '6408e893ef66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'name', name='uq_attribute_org_name')
    )
    op.create_index(op.f('ix_attributes_org_id'), 'attributes', ['org_id'], unique=False)
    op.create_table('attribute_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('attribute_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attribute_id'], ['attributes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attribute_id', 'value', name='uq_attrvalue_attr_value')
    )
    op.create_index(op.f('ix_attribute_values_attribute_id'), 'attribute_values', ['attribute_id'], unique=False)
    op.create_index(op.f('ix_attribute_values_org_id'), 'attribute_values', ['org_id'], unique=False)
    op.create_table('product_attribute_values',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('attribute_value_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attribute_value_id'], ['attribute_values.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'attribute_value_id')
    )
    op.create_table('variant_values',
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('attribute_value_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attribute_value_id'], ['attribute_values.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('variant_id', 'attribute_value_id')
    )
    op.drop_column('product_variants', 'options')
    op.drop_column('products', 'variant_attributes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('variant_attributes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('product_variants', sa.Column('options', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_table('variant_values')
    op.drop_table('product_attribute_values')
    op.drop_index(op.f('ix_attribute_values_org_id'), table_name='attribute_values')
    op.drop_index(op.f('ix_attribute_values_attribute_id'), table_name='attribute_values')
    op.drop_table('attribute_values')
    op.drop_index(op.f('ix_attributes_org_id'), table_name='attributes')
    op.drop_table('attributes')
    # ### end Alembic commands ###
